package com.rwtema.minesouls.coremod;

import java.util.Map;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.relauncher.IFMLLoadingPlugin;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@IFMLLoadingPlugin.TransformerExclusions(value = {"com.rwtema.minesouls.coremod"})
public class MineSoulsControlsCoreMod implements IFMLLoadingPlugin {
	protected static final ModMetadata md;
	public static boolean runtimeDeobfuscationEnabled;

	public static boolean loaded = false;
	public static Logger logger = LogManager.getLogger("MineSoulsControlsCoreMod");

	static {
		md = new ModMetadata();
		md.autogenerated = false;
		md.authorList.add("RWTema");
		md.credits = "RWTema";
		md.modId = "MineSoulsControlsCoreMod";
		md.version = "1";
		md.name = "MineSoulsControlsCoreMod";
		md.description = "Core mod for Mine Souls";
	}

	public MineSoulsControlsCoreMod() {
		loaded = true;
		logger.info("Mine Souls Core Mod - Successfully loaded");
	}

	@Override
	public String[] getASMTransformerClass() {
		return new String[]{MineSoulsControlsTransformer.class.getName()};
	}

	@Override
	public String getModContainerClass() {
		return null;
	}

	@Override
	public String getSetupClass() {
		return null;
	}

	@Override
	public void injectData(Map<String, Object> data) {
		runtimeDeobfuscationEnabled = (Boolean) data.get("runtimeDeobfuscationEnabled");
//		if (!runtimeDeobfuscationEnabled) {
//			try {
//				ClassTransformerHandler.transformers.add(LangGetterTransformer.class.newInstance());
//			} catch (Exception e) {
//				throw Throwables.propagate(e);
//			}
//		}
	}

	@Override
	public String getAccessTransformerClass() {
		return null;
	}

}
